import { query } from "../../db/postgres.js";

export async function getConceptState(userId: string, conceptId: string) {
  const result = await query<any>(`SELECT c.id,c.name,c.mastery,rs.due_at AS "nextReviewAt", max(r.submitted_at) AS "lastRecallAt", COALESCE(avg(r.confidence)/10,0) AS confidence, COALESCE(avg(e.overall_coverage),0) AS "recallSuccessRate", COALESCE(sum(array_length(e.mistakes,1)),0)::int AS "mistakeCount" FROM personal_concepts c LEFT JOIN recall_attempts r ON r.concept_id=c.id AND r.user_id=c.user_id LEFT JOIN recall_evaluations e ON e.recall_attempt_id=r.id LEFT JOIN review_states rs ON rs.concept_id=c.id AND rs.user_id=c.user_id WHERE c.id=$1 AND c.user_id=$2 GROUP BY c.id,rs.due_at`, [conceptId,userId]);
  const row = result.rows[0]; if (!row) return null; const mastery = Number(row.mastery);
  const dimensions = await query<any>(`SELECT dimension,ROUND(AVG(score),3)::float AS score,COUNT(*)::int AS attempts FROM recall_dimension_results d JOIN recall_attempts r ON r.id=d.recall_attempt_id WHERE r.user_id=$1 AND r.concept_id=$2 GROUP BY dimension`, [userId,conceptId]);
  const dimensionScores = Object.fromEntries(["recognition","recall","explanation","application","depth","transfer"].map((name) => [name, dimensions.rows.find((item) => item.dimension === name)?.score ?? null]));
  return { conceptId: row.id, conceptName: row.name, mastery, confidence: Number(row.confidence), recallSuccessRate: Number(row.recallSuccessRate), mistakeCount: row.mistakeCount, lastRecallAt: row.lastRecallAt, nextReviewAt: row.nextReviewAt, dimensionScores, status: mastery < 0.35 ? "needs_review" : mastery < 0.6 ? "weak" : mastery < 0.8 ? "learning" : "stable" };
}
export async function getWeakConcepts(userId: string, limit = 10) { const result = await query<any>(`SELECT id FROM personal_concepts WHERE user_id=$1 AND mastery < 0.7 ORDER BY mastery,updated_at DESC LIMIT $2`, [userId,limit]); const rows=[]; for (const row of result.rows) { const state=await getConceptState(userId,row.id); if(state) rows.push(state); } return rows; }
export async function getWeakSkills(userId: string) { const result=await query<any>(`SELECT id AS "skillId",name,priority,target_mastery AS "targetMastery",current_mastery AS "currentMastery" FROM learner_skills WHERE user_id=$1 ORDER BY current_mastery,priority DESC`, [userId]); return result.rows.map((row) => ({ ...row, targetMastery:Number(row.targetMastery), currentMastery:Number(row.currentMastery), status:Number(row.currentMastery)<0.6?"weak":Number(row.currentMastery)<0.8?"learning":"stable" })); }
export async function getLearnerSummary(userId: string) {
  const concepts=await query<any>(`SELECT mastery FROM personal_concepts WHERE user_id=$1`,[userId]); const weakConcepts=await getWeakConcepts(userId,10); const weakSkills=await getWeakSkills(userId); const due=await query(`SELECT count(*)::int AS count FROM review_states WHERE user_id=$1 AND due_at <= now()`,[userId]); const mistakes=await query<any>(`SELECT r.concept_id AS "conceptId",e.mistakes,r.submitted_at AS "submittedAt" FROM recall_attempts r JOIN recall_evaluations e ON e.recall_attempt_id=r.id WHERE r.user_id=$1 AND cardinality(e.mistakes)>0 ORDER BY r.submitted_at DESC LIMIT 10`,[userId]); const average=concepts.rows.length?concepts.rows.reduce((sum,row)=>sum+Number(row.mastery),0)/concepts.rows.length:0;
  return { totalConcepts:concepts.rows.length, averageMastery:average, dueConcepts:due.rows[0].count, weakConceptCount:weakConcepts.length, weakSkills, weakConcepts, recentMistakes:mistakes.rows, derivedFrom:["concept mastery","recall coverage","review due dates","confidence and mistake history"], heuristics:["weak concepts are below 0.7 mastery","status uses deterministic thresholds"] };
}
