import { query } from "../../db/postgres.js";

export async function getConceptState(userId: string, conceptId: string) {
  const result = await query<any>(`SELECT c.id,c.name,c.mastery,rs.due_at AS "nextReviewAt",
    (SELECT max(r.submitted_at) FROM recall_attempts r WHERE r.concept_id=c.id AND r.user_id=c.user_id AND r.submitted_at IS NOT NULL) AS "lastAttemptAt",
    (SELECT avg(r.confidence)/10 FROM recall_attempts r WHERE r.concept_id=c.id AND r.user_id=c.user_id AND r.submitted_at IS NOT NULL)::float AS confidence,
    (SELECT avg(e.overall_coverage) FROM recall_attempts r JOIN recall_evaluations e ON e.recall_attempt_id=r.id WHERE r.concept_id=c.id AND r.user_id=c.user_id)::float AS "successRate",
    (SELECT count(*)::int FROM recall_attempts r WHERE r.concept_id=c.id AND r.user_id=c.user_id AND r.submitted_at IS NOT NULL) AS "attemptCount",
    (SELECT avg(r.hints_used) FROM recall_attempts r WHERE r.concept_id=c.id AND r.user_id=c.user_id AND r.submitted_at IS NOT NULL)::float AS "hintsUsed",
    COALESCE((SELECT sum(array_length(e.mistakes,1)) FROM recall_attempts r JOIN recall_evaluations e ON e.recall_attempt_id=r.id WHERE r.concept_id=c.id AND r.user_id=c.user_id),0)::int AS "mistakeCount"
    FROM personal_concepts c LEFT JOIN review_states rs ON rs.concept_id=c.id AND rs.user_id=c.user_id WHERE c.id=$1 AND c.user_id=$2`, [conceptId,userId]);
  const row = result.rows[0]; if (!row) return null; const hasEvidence=Number(row.attemptCount)>0; const mastery = hasEvidence?Number(row.mastery):null;
  const dimensions = await query<any>(`SELECT dimension,ROUND(AVG(score),3)::float AS score,COUNT(*)::int AS attempts FROM recall_dimension_results d JOIN recall_attempts r ON r.id=d.recall_attempt_id WHERE r.user_id=$1 AND r.concept_id=$2 GROUP BY dimension`, [userId,conceptId]);
  const pointStates=await query<any>(`SELECT point,mastery::float AS mastery,attempt_count AS "attemptCount",last_status AS "lastStatus",updated_at AS "updatedAt" FROM learner_knowledge_point_states WHERE user_id=$1 AND concept_id=$2 ORDER BY point`,[userId,conceptId]);
  const dimensionScores = Object.fromEntries(["recognition","recall","explanation","application","depth","transfer"].map((name) => [name, dimensions.rows.find((item) => item.dimension === name)?.score ?? null]));
  return { conceptId: row.id, conceptName: row.name, mastery, confidence: row.confidence==null?null:Number(row.confidence), successRate: row.successRate==null?null:Number(row.successRate), attemptCount: Number(row.attemptCount), hintsUsed: row.hintsUsed==null?null:Number(row.hintsUsed), mistakeCount: Number(row.mistakeCount), lastAttemptAt: row.lastAttemptAt, nextReviewAt: row.nextReviewAt, dimensionScores, knowledgePointStates:pointStates.rows, status: !hasEvidence?"new":mastery! < 0.35 ? "needs_review" : mastery! < 0.6 ? "weak" : mastery! < 0.8 ? "learning" : "stable" };
}
export async function getWeakConcepts(userId: string, limit = 10) { const result = await query<any>(`SELECT c.id FROM personal_concepts c WHERE c.user_id=$1 AND c.mastery < 0.7 AND EXISTS(SELECT 1 FROM recall_attempts r WHERE r.user_id=c.user_id AND r.concept_id=c.id AND r.submitted_at IS NOT NULL) ORDER BY c.mastery,c.updated_at DESC LIMIT $2`, [userId,limit]); const rows=[]; for (const row of result.rows) { const state=await getConceptState(userId,row.id); if(state) rows.push(state); } return rows; }
export async function getWeakSkills(userId: string) { const result=await query<any>(`SELECT s.id AS "skillId",s.name,s.priority,s.target_mastery AS "targetMastery",e.mastery AS "currentMastery" FROM learner_skills s LEFT JOIN LATERAL (SELECT AVG(c.mastery)::float AS mastery FROM personal_concepts c WHERE c.user_id=s.user_id AND lower(c.name)=lower(s.name) AND EXISTS(SELECT 1 FROM recall_attempts r WHERE r.user_id=c.user_id AND r.concept_id=c.id AND r.submitted_at IS NOT NULL)) e ON true WHERE s.user_id=$1 ORDER BY e.mastery NULLS FIRST,s.priority DESC`, [userId]); return result.rows.map((row) => ({ ...row, targetMastery:Number(row.targetMastery), currentMastery:row.currentMastery==null?null:Number(row.currentMastery), status:row.currentMastery==null?"new":Number(row.currentMastery)<0.6?"weak":Number(row.currentMastery)<0.8?"learning":"stable" })); }
export async function getLearnerSummary(userId: string) {
  const concepts=await query<any>(`SELECT c.mastery FROM personal_concepts c WHERE c.user_id=$1 AND EXISTS(SELECT 1 FROM recall_attempts r WHERE r.user_id=c.user_id AND r.concept_id=c.id AND r.submitted_at IS NOT NULL)`,[userId]); const total=await query<any>(`SELECT count(*)::int AS count FROM personal_concepts WHERE user_id=$1`,[userId]);const weakConcepts=await getWeakConcepts(userId,10); const weakSkills=await getWeakSkills(userId); const due=await query(`SELECT count(*)::int AS count FROM review_states WHERE user_id=$1 AND due_at <= now()`,[userId]); const mistakes=await query<any>(`SELECT r.concept_id AS "conceptId",e.mistakes,r.submitted_at AS "submittedAt" FROM recall_attempts r JOIN recall_evaluations e ON e.recall_attempt_id=r.id WHERE r.user_id=$1 AND cardinality(e.mistakes)>0 ORDER BY r.submitted_at DESC LIMIT 10`,[userId]); const average=concepts.rows.length?concepts.rows.reduce((sum,row)=>sum+Number(row.mastery),0)/concepts.rows.length:null;
  return { totalConcepts:Number(total.rows[0].count), assessedConcepts:concepts.rows.length, averageMastery:average, dueConcepts:due.rows[0].count, weakConceptCount:weakConcepts.length, weakSkills, weakConcepts, recentMistakes:mistakes.rows, derivedFrom:["concept mastery after submitted attempts","recall coverage","review due dates","confidence and mistake history"], heuristics:["weak concepts are below 0.7 mastery after an attempt","status uses deterministic thresholds"] };
}
