import { useEffect, useState } from "react";
import { ArrowRight, BookOpen } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { api } from "../api/client";
import { EmptyState, PageHeader } from "../components/Ui";
import { ApiError, type GroundedRemediation } from "../types";

export function GroundedRemediationPage() {
  const {id}=useParams();const navigate=useNavigate();const [remediation,setRemediation]=useState<GroundedRemediation|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>{if(id)void api.getRemediation(id).then((result)=>setRemediation(result.remediation)).catch((err)=>setError(err instanceof ApiError&&err.status===404?"This focused review could not be found.":"We couldn’t load this focused review."));},[id]);
  async function verify(){if(!id)return;setBusy(true);setError(null);try{const result=await api.verifyRemediation(id);navigate(`/recall/${result.attempt.id}`);}catch{setError("We couldn’t start the recall check. Please try again.");}finally{setBusy(false);}}
  if(error&&!remediation)return <p className="error" role="alert">{error} <Link to="/dashboard">Return to dashboard</Link></p>;if(!remediation)return <div className="card grid"><div className="skeleton"/><div className="skeleton"/></div>;
  const content=remediation.content;const status=remediation.status;const stateLabel=status==="ready"?"Ready to review":status==="verified"?"Review complete":status==="verification_created"?"Recall in progress":status==="insufficient_sources"?"No supporting material found":"Preparing your review";
  return <div className="grid"><PageHeader eyebrow="Focused review" title={content?.title??remediation.conceptName} description={remediation.reason}/><section className="remediation-focus card"><span className="status-chip">{stateLabel}</span><div><p className="eyebrow">FOCUS ON</p><h2>{remediation.knowledgePoint}</h2></div></section>
    {error?<p className="error" role="alert">{error}</p>:null}
    {status==="insufficient_sources"?<article className="card"><h2>We couldn’t find material for this exact gap</h2><p className="muted">The source excerpts weren’t specific enough to prepare an explanation. These resources may still help:</p>{remediation.fallbackResources.map((resource)=><p key={resource.id}><a href={resource.url} target="_blank" rel="noreferrer">{resource.title}</a> · {resource.estimatedMinutes} min</p>)}</article>:null}
    {status==="failed"?<article className="card"><h2>This review couldn’t be prepared</h2><p className="muted">The source material is retained below. You can also use one of these resources to revisit the concept.</p>{remediation.fallbackResources.map((resource)=><p key={resource.id}><a href={resource.url} target="_blank" rel="noreferrer">{resource.title}</a> · {resource.estimatedMinutes} min</p>)}</article>:null}
    {content?<article className="card remediation-explanation"><p className="eyebrow">A focused explanation</p><p>{content.explanation}</p><h3>Key ideas</h3><ul>{content.keyPoints.map((point,index)=><li key={index}>{point}</li>)}</ul><h3>What to watch for</h3><p>{content.commonMistake}</p><h3>Check yourself</h3><ol>{content.checkYourself.map((question,index)=><li key={index}>{question}</li>)}</ol>{content.unsupportedAspects.length?<p className="muted">The available sources don’t cover: {content.unsupportedAspects.join("; ")}</p>:null}</article>:null}
    {remediation.sources.length?<article className="card"><h2>Material for this review</h2>{remediation.sources.map((source)=><div key={source.chunkId} className="source-excerpt"><div className="source-excerpt-title"><strong>{source.title}</strong>{/^https?:\/\//i.test(source.reference)?<a className="metadata" href={source.reference} target="_blank" rel="noreferrer">Original material <ArrowRight size={13}/></a>:null}</div><p className="metadata">{source.sourceType.replaceAll("_"," ")}</p><p>{source.text.slice(0,650)}{source.text.length>650?"…":""}</p></div>)}</article>:null}
    {status==="verified"?<article className="card"><p className="eyebrow">RECALL CHECK</p><h2>{remediation.improved?"You showed stronger evidence":"This point needs more practice"}</h2><p className="muted">We compared your answer with the recall that first surfaced this gap.</p>{remediation.triggerScore!=null&&remediation.verificationScore!=null?<p className="metadata">Before {Math.round(remediation.triggerScore*100)}% · After {Math.round(remediation.verificationScore*100)}%</p>:null}</article>:null}
    {status==="ready"?<button className="btn btn-primary remediation-action" disabled={busy} onClick={()=>void verify()} type="button">{busy?"Getting ready…":"Check what you remember"} <ArrowRight size={15}/></button>:null}
    {status==="verification_created"&&remediation.verificationAttemptId?<Link className="btn btn-primary remediation-action" to={`/recall/${remediation.verificationAttemptId}`}>Continue recall <ArrowRight size={15}/></Link>:null}
    {!content&&!remediation.sources.length&&!remediation.fallbackResources.length&&status!=="verified"?<EmptyState title="No review material is available yet" to="/resources" action="Explore resources" icon={<BookOpen size={18}/>}>Return to your plan or explore another resource while this gap is fresh.</EmptyState>:null}
  </div>;
}
