import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowRight, Check, Clock3, Compass, Target } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../api/client";
import { PageHeader } from "../components/Ui";
import type { KnowledgeRole } from "../types";

const goalChoices=["Backend Engineer","Software Engineering Interviews","CS Fundamentals","System Design","Programming Language","Custom Goal"];
const outcomes=["Understand fundamentals","Build production systems","Interview ready","All of these"];
const timeChoices=[{label:"15 min/day",minutes:105},{label:"30 min/day",minutes:210},{label:"45 min/day",minutes:315},{label:"1 hr/day",minutes:420}];
const startingPoints=[{value:"new",label:"New to it",detail:"Start with the foundations."},{value:"familiar",label:"Studied before",detail:"Check what stayed with you."},{value:"sometimes",label:"Use it sometimes",detail:"See which ideas are solid."},{value:"advanced",label:"Think I know it well",detail:"Start with a deeper check."},{value:"not_sure",label:"Not sure",detail:"Study first; we won’t guess."}];

export function OnboardingPage(){
  const navigate=useNavigate();const [roles,setRoles]=useState<KnowledgeRole[]>([]);const [rolesLoading,setRolesLoading]=useState(true);const [goalChoice,setGoalChoice]=useState(goalChoices[0]);const [customTitle,setCustomTitle]=useState("");const [outcome,setOutcome]=useState(outcomes[0]);const [minutes,setMinutes]=useState(210);const [customMinutes,setCustomMinutes]=useState(300);const [useCustomTime,setUseCustomTime]=useState(false);const [starting,setStarting]=useState("not_sure");const [skillId,setSkillId]=useState("");const [customTopic,setCustomTopic]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [createdGoalId,setCreatedGoalId]=useState<string|null>(null);
  useEffect(()=>{void api.knowledgeRoles().then((result)=>setRoles(result.roles)).catch(()=>setRoles([])).finally(()=>setRolesLoading(false));},[]);
  const skills=useMemo(()=>roles.flatMap((role)=>role.skills.map((skill)=>({id:skill.id,name:skill.name,role:role.name}))),[roles]);
  const title=goalChoice==="Custom Goal"?customTitle.trim():goalChoice;const selectedSkill=skills.find((skill)=>skill.id===skillId);const topic=selectedSkill?.name??customTopic.trim();
  async function submit(event:FormEvent){event.preventDefault();if(createdGoalId)return;setBusy(true);setError(null);try{
    const goalType=goalChoice.includes("Interview")?"interview":goalChoice==="Backend Engineer"?"career":"learning";
    const {goal}=await api.createGoal({title,description:outcome,goalType,weeklyTimeBudgetMinutes:useCustomTime?customMinutes:minutes});setCreatedGoalId(goal.id);
    if(topic)await api.createSkill(goal.id,{name:topic,description:selectedSkill?`Knowledge map focus: ${selectedSkill.role}.`:"First focus area for this goal.",priority:90});
    if(starting!=="not_sure"&&selectedSkill){const level=starting==="new"?"new":starting==="advanced"?"advanced":"familiar";const result=await api.createBaseline({goalId:goal.id,skillId:selectedSkill.id,level});navigate(`/baseline/${result.baseline.assessment.id}${result.baseline.questions.length?"":"/result"}`);return;}
    navigate(topic?`/study/new?topic=${encodeURIComponent(topic)}&goalId=${encodeURIComponent(goal.id)}`:`/goals/${goal.id}`);
  }catch{setError(createdGoalId?"Your goal was saved, but we couldn’t finish the next step. Continue to your goal and pick up from there.":"We couldn’t save your goal. Please try again.");}finally{setBusy(false);}}
  return <div className="onboarding-wrap"><Link className="onboarding-skip" to="/dashboard">Skip setup</Link><PageHeader eyebrow="Your first steps · 1 of 1" title="Let’s make a learning plan that fits you" description="A few choices help RecallLoop find a useful place to begin. You can change your goal and schedule later."/>
    <form className="onboarding-form" onSubmit={(event)=>void submit(event)}>
      <section className="onboarding-section"><div className="onboarding-section-title"><span>01</span><div><h2>What are you working toward?</h2><p className="muted">Choose a direction. You can make it your own.</p></div></div><div className="choice-grid">{goalChoices.map((choice)=><button key={choice} className={`choice-card ${goalChoice===choice?"selected":""}`} type="button" aria-pressed={goalChoice===choice} onClick={()=>setGoalChoice(choice)}><Target size={17}/>{choice}{goalChoice===choice?<Check className="choice-check" size={15}/>:null}</button>)}</div>{goalChoice==="Custom Goal"?<label htmlFor="custom-goal">Name your goal<input id="custom-goal" required value={customTitle} onChange={(event)=>setCustomTitle(event.target.value)} placeholder="What do you want to learn?"/></label>:null}<label htmlFor="goal-outcome">What does “good” mean to you?</label><select id="goal-outcome" value={outcome} onChange={(event)=>setOutcome(event.target.value)}>{outcomes.map((item)=><option key={item}>{item}</option>)}</select></section>
      <section className="onboarding-section"><div className="onboarding-section-title"><span>02</span><div><h2>How much time can you give it?</h2><p className="muted">We’ll use this to shape your daily plan.</p></div></div><div className="time-choice-grid">{timeChoices.map((item)=><button key={item.minutes} className={`time-choice-card ${!useCustomTime&&minutes===item.minutes?"selected":""}`} type="button" aria-pressed={!useCustomTime&&minutes===item.minutes} onClick={()=>{setMinutes(item.minutes);setUseCustomTime(false);}}><Clock3 size={15}/>{item.label}</button>)}<button className={`time-choice-card ${useCustomTime?"selected":""}`} type="button" aria-pressed={useCustomTime} onClick={()=>setUseCustomTime(true)}>Custom</button></div>{useCustomTime?<label htmlFor="custom-time">Minutes each week<input id="custom-time" type="number" min={60} max={840} step={15} value={customMinutes} onChange={(event)=>setCustomMinutes(Math.max(60,Math.min(840,Number(event.target.value))))}/></label>:null}</section>
      <section className="onboarding-section"><div className="onboarding-section-title"><span>03</span><div><h2>Where should we start?</h2><p className="muted">Your starting point helps choose the first useful activity.</p></div></div><div className="starting-options">{startingPoints.map((item)=><button key={item.value} className={`starting-option ${starting===item.value?"selected":""}`} type="button" aria-pressed={starting===item.value} onClick={()=>setStarting(item.value)}><span>{item.label}</span><small>{item.detail}</small></button>)}</div><label htmlFor="start-topic">Choose a focus area</label>{rolesLoading?<div className="skeleton onboarding-skeleton" role="status" aria-label="Loading focus areas"/>:skills.length?<select required id="start-topic" value={skillId} onChange={(event)=>{setSkillId(event.target.value);setCustomTopic("");}}><option value="">Choose a topic from the knowledge map</option>{roles.map((role)=><optgroup key={role.id} label={role.name}>{role.skills.map((skill)=><option key={skill.id} value={skill.id}>{skill.name}</option>)}</optgroup>)}</select>:<><p className="metadata">The knowledge map isn’t available right now. You can start with your own topic.</p><label htmlFor="custom-topic">First topic<input id="custom-topic" required value={customTopic} onChange={(event)=>setCustomTopic(event.target.value)} placeholder="e.g. HTTP caching"/></label></>}{skillId?<p className="metadata">We’ll start with {selectedSkill?.name} in your first learning activity.</p>:null}</section>
      {error?<div className="error" role="alert">{error}{createdGoalId?<p><Link to={`/goals/${createdGoalId}`}>Continue to your saved goal <ArrowRight size={14}/></Link></p>:null}</div>:null}
      <div className="onboarding-footer"><span className="metadata"><Compass size={14}/> Your progress is based on recall evidence, not time spent.</span><button className="btn btn-primary" type="submit" disabled={busy||!!createdGoalId||!title||!topic||rolesLoading}>{busy?"Setting things up…":starting==="not_sure"||!selectedSkill?"Start studying":"Continue to starting check"} <ArrowRight size={15}/></button></div>
    </form>
  </div>;
}
