import { useEffect,useState } from "react";
import { useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import { ApiError,type ResourceRecommendation } from "../types";

export function ResourcesPage(){
  const [search]=useSearchParams();const conceptId=search.get("conceptId")??"";
  const [available,setAvailable]=useState(60);const [resources,setResources]=useState<ResourceRecommendation[]>([]);const [pack,setPack]=useState<Awaited<ReturnType<typeof api.learningPack>>["pack"]|null>(null);const [error,setError]=useState<string|null>(null);
  async function load(){try{const [resourceResult,packResult]=await Promise.all([api.recommendedResources(conceptId,available),conceptId?api.learningPack(conceptId,available):Promise.resolve(null)]);setResources(resourceResult.resources);setPack(packResult?.pack??null);setError(null);}catch(err){setError(err instanceof ApiError?err.message:"Could not load focused resources");}}
  useEffect(()=>{if(conceptId)void load();},[conceptId]);
  return <div><section className="hero"><h1>Focused resources</h1><p>Resources are ranked against the concept gap, learner evidence, source quality, freshness, and your available time.</p><label>Available minutes<input type="number" min={0} max={240} value={available} onChange={(event)=>setAvailable(Number(event.target.value))}/></label><button className="btn btn-primary" type="button" onClick={()=>void load()}>Update recommendations</button></section>{error?<p className="error">{error}</p>:null}{pack?<section className="card"><h2>Learning Pack · {pack.conceptName}</h2><p>{pack.estimatedTotalMinutes} min of {pack.availableMinutes} available · {pack.remainingMinutes} min remaining</p>{pack.items.map((item,index)=><article className="row" key={`${item.kind}-${index}`}><span className="badge">{item.minutes} min · {item.kind}</span>{item.url?<a href={item.url} target="_blank" rel="noreferrer">{item.title}</a>:<strong>{item.title}</strong>}<p className="muted">{item.reason}</p></article>)}</section>:null}<section className="grid" style={{marginTop:16}}>{resources.map((resource)=><article className="card" key={resource.id}><a href={resource.url} target="_blank" rel="noreferrer"><h2>{resource.title}</h2></a><p>{resource.description}</p><p className="muted">{resource.estimatedMinutes} min · Difficulty {resource.difficulty} · Trust tier {resource.trustTier}{resource.freshness?` · ${resource.freshness}`:""}</p><p>Concepts covered: {resource.conceptsCovered.join(", ")}</p><p>{resource.reason}</p></article>)}</section>{conceptId&&resources.length===0&&!error?<p className="muted">No resource with matching coverage fits this time budget.</p>:null}</div>;
}
