import { query, withTransaction } from "../db/postgres.js";

export function mapSession(row: any) { return { id: row.id, userId: row.user_id, title: row.title, rawMaterial: row.raw_material, sourceType: row.source_type, startedAt: row.started_at, completedAt: row.completed_at, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapConcept(row: any) { return { id: row.id, userId: row.user_id, studySessionId: row.study_session_id, name: row.name, description: row.description, parentConceptId: row.parent_concept_id, requiredKnowledgePoints: row.required_knowledge_points, difficulty: row.difficulty, mastery: Number(row.mastery), createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapReview(row: any) { return row ? { id: row.id, userId: row.user_id, conceptId: row.concept_id, state: row.state, dueAt: row.due_at, intervalDays: row.interval_days, stability: Number(row.stability), difficulty: Number(row.difficulty), lastRecallAt: row.last_recall_at, lastOutcome: row.last_outcome, consecutiveSuccesses: row.consecutive_successes, updatedAt: row.updated_at } : null; }

async function evaluationForAttempt(attemptId: string) {
  const result = await query<any>(`SELECT e.*, COALESCE(json_agg(json_build_object('point',r.point,'status',r.status,'evidence',r.evidence,'feedback',r.feedback) ORDER BY r.id) FILTER (WHERE r.id IS NOT NULL), '[]') AS knowledge_point_results FROM recall_evaluations e LEFT JOIN recall_knowledge_point_results r ON r.evaluation_id=e.id WHERE e.recall_attempt_id=$1 GROUP BY e.id`, [attemptId]);
  const row = result.rows[0];
  return row ? { overallCoverage: Number(row.overall_coverage), knowledgePointResults: row.knowledge_point_results, missingConcepts: row.missing_concepts, mistakes: row.mistakes, strengths: row.strengths, feedback: row.feedback, suggestedRecallType: row.suggested_recall_type, evaluatorVersion: row.evaluator_version } : null;
}
export async function getAttempt(id: string, userId: string) {
  const result = await query<any>(`SELECT * FROM recall_attempts WHERE id=$1 AND user_id=$2`, [id,userId]);
  if (!result.rows[0]) return null;
  const row = result.rows[0];
  const questionResult = row.question_id ? await query<any>(`SELECT * FROM questions WHERE id=$1`, [row.question_id]) : { rows: [] } as any;
  const question = questionResult.rows[0];
  const recommendationResult = await query<any>(`SELECT action_type AS "actionType",title,reason,estimated_minutes AS "estimatedMinutes",priority FROM assessment_recommendations WHERE recall_attempt_id=$1`,[id]);
  return { ...row, id: row.id, conceptId: row.concept_id, studySessionId: row.study_session_id, questionType: row.question_type, answer: row.answer, confidence: row.confidence, submittedAt: row.submitted_at, createdAt: row.created_at, startedAt: row.started_at, timeTakenSeconds: row.time_taken_seconds, selectedOptionId: row.selected_option_id, hintsUsed: row.hints_used, maxHintLevel: row.max_hint_level, hintTimestamps: row.hint_timestamps, repetitionReason: row.repetition_reason, remediationId: row.remediation_id, resultStatus: row.result_status, evidenceWeight: Number(row.evidence_weight ?? 1), question: question ? { id: question.id, assessmentLevel: question.assessment_level, difficulty: question.difficulty, title: question.title, context: question.context, prompt: question.prompt, estimatedMinutes: question.estimated_minutes, source: question.source, options: question.options, correctOptionId: question.correct_option_id, explanation: question.explanation, knowledgePoints: question.knowledge_points, repetitionReason: row.repetition_reason, revealedHints: question.hints.slice(0, row.max_hint_level ?? 0), hintsRemaining: Math.max(0, question.hints.length - (row.max_hint_level ?? 0)) } : null, recommendation: recommendationResult.rows[0] ?? null, evaluation: await evaluationForAttempt(id) };
}
export async function getConcept(id: string, userId: string) { const result = await query<any>(`SELECT * FROM personal_concepts WHERE id=$1 AND user_id=$2`, [id,userId]); return result.rows[0] ? mapConcept(result.rows[0]) : null; }
export async function createSession(userId: string, input: any) { const result = await query(`INSERT INTO study_sessions (user_id,title,raw_material,source_type) VALUES ($1,$2,$3,$4) RETURNING *`, [userId,input.title,input.rawMaterial ?? "",input.sourceType ?? "manual"]); return mapSession(result.rows[0]); }
export async function getSession(id: string, userId: string) { const result = await query(`SELECT * FROM study_sessions WHERE id=$1 AND user_id=$2`, [id,userId]); return result.rows[0] ? mapSession(result.rows[0]) : null; }
export async function completeSession(id: string, userId: string) { const result = await query(`UPDATE study_sessions SET status='completed',completed_at=COALESCE(completed_at,now()),updated_at=now() WHERE id=$1 AND user_id=$2 RETURNING *`, [id,userId]); return result.rows[0] ? mapSession(result.rows[0]) : null; }
export async function createConcepts(userId: string, sessionId: string, concepts: any[]) { const rows = []; for (const concept of concepts) { const result = await query(`INSERT INTO personal_concepts (user_id,study_session_id,name,description,required_knowledge_points,difficulty) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`, [userId,sessionId,concept.name,concept.description,concept.requiredKnowledgePoints,concept.difficulty ?? 3]); rows.push(mapConcept(result.rows[0])); } return rows; }
export async function listConceptsForSession(sessionId: string, userId: string) { const result = await query(`SELECT * FROM personal_concepts WHERE study_session_id=$1 AND user_id=$2 ORDER BY created_at`, [sessionId,userId]); return result.rows.map(mapConcept); }
export async function updateConceptMastery(id: string, userId: string, coverage: number) { const result = await query(`UPDATE personal_concepts SET mastery=ROUND((mastery * 0.4 + $3 * 0.6)::numeric,4),updated_at=now() WHERE id=$1 AND user_id=$2 RETURNING *`, [id,userId,coverage]); return result.rows[0] ? mapConcept(result.rows[0]) : null; }
export async function createAttempt(userId: string, sessionId: string, concept: any, questionType: string, question: string) { const existing = await query(`SELECT * FROM recall_attempts WHERE user_id=$1 AND concept_id=$2 AND submitted_at IS NULL ORDER BY created_at LIMIT 1`, [userId,concept.id]); if (existing.rows[0]) return getAttempt(existing.rows[0].id,userId); const result = await query(`INSERT INTO recall_attempts (user_id,concept_id,study_session_id,question_type,question) VALUES ($1,$2,$3,$4,$5) RETURNING id`, [userId,concept.id,sessionId,questionType,question]); return getAttempt(result.rows[0].id,userId); }
export async function listPending(sessionId: string, userId: string) { const result = await query(`SELECT id FROM recall_attempts WHERE study_session_id=$1 AND user_id=$2 AND submitted_at IS NULL ORDER BY created_at`, [sessionId,userId]); const rows = []; for (const row of result.rows) rows.push(await getAttempt(row.id,userId)); return rows.filter(Boolean); }
export async function createInitialReview(userId: string, conceptId: string, difficulty: number) { await query(`INSERT INTO review_states (user_id,concept_id,state,due_at,difficulty) VALUES ($1,$2,'new',now(),$3) ON CONFLICT (user_id,concept_id) DO UPDATE SET due_at=LEAST(review_states.due_at,EXCLUDED.due_at),updated_at=now()`, [userId,conceptId,difficulty/5]); }
export async function getReview(userId: string, conceptId: string) { const result = await query(`SELECT * FROM review_states WHERE user_id=$1 AND concept_id=$2`, [userId,conceptId]); return mapReview(result.rows[0]); }
export async function revealNextHint(userId: string, attemptId: string) {
  const result = await query<any>(`UPDATE recall_attempts SET hints_used=hints_used+1,max_hint_level=max_hint_level+1,hint_timestamps=array_append(hint_timestamps,now()) WHERE id=$1 AND user_id=$2 AND submitted_at IS NULL AND max_hint_level < 3 AND max_hint_level < COALESCE((SELECT cardinality(q.hints) FROM questions q WHERE q.id=recall_attempts.question_id),0) RETURNING max_hint_level`, [attemptId,userId]);
  if (!result.rows[0]) return null;
  const hintResult = await query<any>(`SELECT q.hints[$2] AS hint FROM recall_attempts r JOIN questions q ON q.id=r.question_id WHERE r.id=$1 AND r.user_id=$3`, [attemptId,result.rows[0].max_hint_level,userId]);
  return { hint: hintResult.rows[0]?.hint ?? null, maxHintLevel: result.rows[0].max_hint_level };
}

export async function submitAttempt(userId: string, attemptId: string, answer: string, confidence: number, evaluation: any, scheduled: any, conceptId: string, mastery: number, input: { selectedOptionId?: string | null; resultStatus: string; evidenceWeight: number; recommendation: any }) {
  const written = await withTransaction(async (client) => {
    const result = await client.query(`UPDATE recall_attempts SET answer=$3,confidence=$4,selected_option_id=$5,submitted_at=now(),time_taken_seconds=GREATEST(0,FLOOR(EXTRACT(EPOCH FROM (now()-started_at)))::int),result_status=$6,evidence_weight=$7 WHERE id=$1 AND user_id=$2 AND submitted_at IS NULL RETURNING id`, [attemptId,userId,answer,confidence,input.selectedOptionId ?? null,input.resultStatus,input.evidenceWeight]);
    if (!result.rows[0]) return null;
    const evaluationResult = await client.query(`INSERT INTO recall_evaluations (recall_attempt_id,overall_coverage,missing_concepts,mistakes,strengths,feedback,suggested_recall_type,evaluator_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`, [attemptId,evaluation.overallCoverage,evaluation.missingConcepts,evaluation.mistakes,evaluation.strengths,evaluation.feedback,evaluation.suggestedRecallType,evaluation.evaluatorVersion]);
    for (const point of evaluation.knowledgePointResults) await client.query(`INSERT INTO recall_knowledge_point_results (evaluation_id,point,status,evidence,feedback) VALUES ($1,$2,$3,$4,$5)`, [evaluationResult.rows[0].id,point.point,point.status,point.evidence,point.feedback]);
    const remediationResult=await client.query<any>(`SELECT a.remediation_id AS id,r.knowledge_point,r.trigger_score FROM recall_attempts a JOIN grounded_remediations r ON r.id=a.remediation_id WHERE a.id=$1`,[attemptId]);
    const remediation=remediationResult.rows[0];
    if(remediation){
      const resultForGap=evaluation.knowledgePointResults.find((point:any)=>point.point.trim().toLowerCase()===remediation.knowledge_point.trim().toLowerCase());
      const verifiedScore=resultForGap?Number((({correct:1,partial:.5,missing:0} as Record<string,number>)[resultForGap.status]??0)*input.evidenceWeight):0;
      const improved=verifiedScore>Number(remediation.trigger_score??0);
      await client.query(`UPDATE grounded_remediations SET status='verified',verification_score=$2,improved=$3,updated_at=now() WHERE id=$1`,[remediation.id,verifiedScore,improved]);
    }
    await client.query(`INSERT INTO assessment_recommendations(recall_attempt_id,action_type,title,reason,estimated_minutes,priority) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(recall_attempt_id) DO UPDATE SET action_type=EXCLUDED.action_type,title=EXCLUDED.title,reason=EXCLUDED.reason,estimated_minutes=EXCLUDED.estimated_minutes,priority=EXCLUDED.priority`,[attemptId,input.recommendation.actionType,input.recommendation.title,input.recommendation.reason,input.recommendation.estimatedMinutes,input.recommendation.priority]);
    const dim = evaluation.dimension ?? "explanation";
    await client.query(`INSERT INTO recall_dimension_results (recall_attempt_id,dimension,score) VALUES ($1,$2,$3) ON CONFLICT (recall_attempt_id,dimension) DO UPDATE SET score=EXCLUDED.score`, [attemptId,dim,Math.max(0,Math.min(1,evaluation.overallCoverage * input.evidenceWeight))]);
    await client.query(`UPDATE personal_concepts SET mastery=$3,updated_at=now() WHERE id=$1 AND user_id=$2`, [conceptId,userId,mastery]);
    await client.query(`INSERT INTO review_states (user_id,concept_id,state,due_at,interval_days,stability,difficulty,last_recall_at,last_outcome,consecutive_successes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (user_id,concept_id) DO UPDATE SET state=EXCLUDED.state,due_at=EXCLUDED.due_at,interval_days=EXCLUDED.interval_days,stability=EXCLUDED.stability,difficulty=EXCLUDED.difficulty,last_recall_at=EXCLUDED.last_recall_at,last_outcome=EXCLUDED.last_outcome,consecutive_successes=EXCLUDED.consecutive_successes,updated_at=now()`, [userId,conceptId,scheduled.state,scheduled.dueAt,scheduled.intervalDays,scheduled.stability,scheduled.difficulty,scheduled.lastRecallAt,scheduled.lastOutcome,scheduled.consecutiveSuccesses]);
    await client.query(`INSERT INTO learning_events (user_id,type,entity_type,entity_id,payload) VALUES ($1,'RECALL_SUBMITTED','RecallAttempt',$2,$3),($1,'EVALUATION_COMPLETED','RecallAttempt',$2,$4),($1,'REVIEW_SCHEDULED','ReviewState',$5,$6)`, [userId,attemptId,JSON.stringify({ confidence }),JSON.stringify({ mistakes: evaluation.mistakes }),conceptId,JSON.stringify({ dueAt: scheduled.dueAt, outcome: scheduled.lastOutcome })]);
    return true;
  });
  return written ? getAttempt(attemptId,userId) : null;
}
