import { query } from "../db/postgres.js";

export function mapSession(row: any) { return { id: row.id, userId: row.user_id, title: row.title, rawMaterial: row.raw_material, sourceType: row.source_type, startedAt: row.started_at, completedAt: row.completed_at, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapConcept(row: any) { return { id: row.id, userId: row.user_id, studySessionId: row.study_session_id, name: row.name, description: row.description, parentConceptId: row.parent_concept_id, requiredKnowledgePoints: row.required_knowledge_points, difficulty: row.difficulty, mastery: Number(row.mastery), createdAt: row.created_at, updatedAt: row.updated_at }; }
export function mapReview(row: any) { return row ? { id: row.id, userId: row.user_id, conceptId: row.concept_id, state: row.state, dueAt: row.due_at, intervalDays: row.interval_days, stability: Number(row.stability), difficulty: Number(row.difficulty), lastRecallAt: row.last_recall_at, lastOutcome: row.last_outcome, consecutiveSuccesses: row.consecutive_successes, updatedAt: row.updated_at } : null; }

async function evaluationForAttempt(attemptId: string) {
  const result = await query<any>(`SELECT e.*, COALESCE(json_agg(json_build_object('point',r.point,'status',r.status,'evidence',r.evidence,'feedback',r.feedback) ORDER BY r.id) FILTER (WHERE r.id IS NOT NULL), '[]') AS knowledge_point_results FROM recall_evaluations e LEFT JOIN recall_knowledge_point_results r ON r.evaluation_id=e.id WHERE e.recall_attempt_id=$1 GROUP BY e.id`, [attemptId]);
  const row = result.rows[0];
  return row ? { overallCoverage: Number(row.overall_coverage), knowledgePointResults: row.knowledge_point_results, missingConcepts: row.missing_concepts, mistakes: row.mistakes, strengths: row.strengths, feedback: row.feedback, suggestedRecallType: row.suggested_recall_type, evaluatorVersion: row.evaluator_version } : null;
}
export async function getAttempt(id: string, userId: string) {
  const result = await query<any>(`SELECT * FROM recall_attempts WHERE id=$1 AND user_id=$2`, [id,userId]);
  if (!result.rows[0]) return null;
  return { ...result.rows[0], id: result.rows[0].id, conceptId: result.rows[0].concept_id, studySessionId: result.rows[0].study_session_id, questionType: result.rows[0].question_type, answer: result.rows[0].answer, confidence: result.rows[0].confidence, submittedAt: result.rows[0].submitted_at, createdAt: result.rows[0].created_at, evaluation: await evaluationForAttempt(id) };
}
export async function getConcept(id: string, userId: string) { const result = await query<any>(`SELECT * FROM personal_concepts WHERE id=$1 AND user_id=$2`, [id,userId]); return result.rows[0] ? mapConcept(result.rows[0]) : null; }
export async function createSession(userId: string, input: any) { const result = await query(`INSERT INTO study_sessions (user_id,title,raw_material,source_type) VALUES ($1,$2,$3,$4) RETURNING *`, [userId,input.title,input.rawMaterial ?? "",input.sourceType ?? "manual"]); return mapSession(result.rows[0]); }
export async function getSession(id: string, userId: string) { const result = await query(`SELECT * FROM study_sessions WHERE id=$1 AND user_id=$2`, [id,userId]); return result.rows[0] ? mapSession(result.rows[0]) : null; }
export async function completeSession(id: string, userId: string) { const result = await query(`UPDATE study_sessions SET status='completed',completed_at=COALESCE(completed_at,now()),updated_at=now() WHERE id=$1 AND user_id=$2 RETURNING *`, [id,userId]); return result.rows[0] ? mapSession(result.rows[0]) : null; }
export async function createConcepts(userId: string, sessionId: string, concepts: any[]) { const rows = []; for (const concept of concepts) { const result = await query(`INSERT INTO personal_concepts (user_id,study_session_id,name,description,required_knowledge_points,difficulty) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`, [userId,sessionId,concept.name,concept.description,concept.requiredKnowledgePoints,concept.difficulty ?? 3]); rows.push(mapConcept(result.rows[0])); } return rows; }
export async function listConceptsForSession(sessionId: string, userId: string) { const result = await query(`SELECT * FROM personal_concepts WHERE study_session_id=$1 AND user_id=$2 ORDER BY created_at`, [sessionId,userId]); return result.rows.map(mapConcept); }
export async function updateConceptMastery(id: string, userId: string, coverage: number) { const result = await query(`UPDATE personal_concepts SET mastery=ROUND((mastery * 0.4 + $3 * 0.6)::numeric,4),updated_at=now() WHERE id=$1 AND user_id=$2 RETURNING *`, [id,userId,coverage]); return result.rows[0] ? mapConcept(result.rows[0]) : null; }
export async function createAttempt(userId: string, sessionId: string, concept: any, questionType: string, question: string) { const existing = await query(`SELECT * FROM recall_attempts WHERE user_id=$1 AND concept_id=$2 AND submitted_at IS NULL ORDER BY created_at LIMIT 1`, [userId,concept.id]); if (existing.rows[0]) return getAttempt(existing.rows[0].id,userId); const result = await query(`INSERT INTO recall_attempts (user_id,concept_id,study_session_id,question_type,question) VALUES ($1,$2,$3,$4,$5) RETURNING id`, [userId,concept.id,sessionId,questionType,question]); return getAttempt(result.rows[0].id,userId); }
export async function listPending(sessionId: string, userId: string) { const result = await query(`SELECT id FROM recall_attempts WHERE study_session_id=$1 AND user_id=$2 AND submitted_at IS NULL ORDER BY created_at`, [sessionId,userId]); const rows = []; for (const row of result.rows) rows.push(await getAttempt(row.id,userId)); return rows.filter(Boolean); }
export async function createInitialReview(userId: string, conceptId: string, difficulty: number) { await query(`INSERT INTO review_states (user_id,concept_id,state,due_at,difficulty) VALUES ($1,$2,'new',now(),$3) ON CONFLICT (user_id,concept_id) DO UPDATE SET due_at=LEAST(review_states.due_at,EXCLUDED.due_at),updated_at=now()`, [userId,conceptId,difficulty/5]); }
export async function getReview(userId: string, conceptId: string) { const result = await query(`SELECT * FROM review_states WHERE user_id=$1 AND concept_id=$2`, [userId,conceptId]); return mapReview(result.rows[0]); }
export async function submitAttempt(userId: string, attemptId: string, answer: string, confidence: number, evaluation: any, scheduled: any, conceptId: string, mastery: number) {
  const result = await query(`UPDATE recall_attempts SET answer=$3,confidence=$4,submitted_at=now() WHERE id=$1 AND user_id=$2 AND submitted_at IS NULL RETURNING *`, [attemptId,userId,answer,confidence]);
  if (!result.rows[0]) return null;
  const evaluationResult = await query(`INSERT INTO recall_evaluations (recall_attempt_id,overall_coverage,missing_concepts,mistakes,strengths,feedback,suggested_recall_type,evaluator_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`, [attemptId,evaluation.overallCoverage,evaluation.missingConcepts,evaluation.mistakes,evaluation.strengths,evaluation.feedback,evaluation.suggestedRecallType,evaluation.evaluatorVersion]);
  for (const point of evaluation.knowledgePointResults) await query(`INSERT INTO recall_knowledge_point_results (evaluation_id,point,status,evidence,feedback) VALUES ($1,$2,$3,$4,$5)`, [evaluationResult.rows[0].id,point.point,point.status,point.evidence,point.feedback]);
  await query(`UPDATE personal_concepts SET mastery=$3,updated_at=now() WHERE id=$1 AND user_id=$2`, [conceptId,userId,mastery]);
  await query(`INSERT INTO review_states (user_id,concept_id,state,due_at,interval_days,stability,difficulty,last_recall_at,last_outcome,consecutive_successes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (user_id,concept_id) DO UPDATE SET state=EXCLUDED.state,due_at=EXCLUDED.due_at,interval_days=EXCLUDED.interval_days,stability=EXCLUDED.stability,difficulty=EXCLUDED.difficulty,last_recall_at=EXCLUDED.last_recall_at,last_outcome=EXCLUDED.last_outcome,consecutive_successes=EXCLUDED.consecutive_successes,updated_at=now()`, [userId,conceptId,scheduled.state,scheduled.dueAt,scheduled.intervalDays,scheduled.stability,scheduled.difficulty,scheduled.lastRecallAt,scheduled.lastOutcome,scheduled.consecutiveSuccesses]);
  return getAttempt(attemptId,userId);
}
